//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class adventuredeck
    {
        public adventuredeck()
        {
            this.cards = new HashSet<card>();
            this.scenarios = new HashSet<scenario>();
            this.allycards = new HashSet<allycard>();
            this.armorcards = new HashSet<armorcard>();
            this.blessingcards = new HashSet<blessingcard>();
            this.itemcards = new HashSet<itemcard>();
            this.spellcards = new HashSet<spellcard>();
            this.weaponcards = new HashSet<weaponcard>();
            this.barriercards = new HashSet<barriercard>();
            this.henchmencards = new HashSet<henchmencard>();
            this.monstercards = new HashSet<monstercard>();
            this.villaincards = new HashSet<villaincard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AdventurePathId { get; set; }
        public int Index { get; set; }
    
        public virtual ICollection<card> cards { get; set; }
        public virtual adventurepath adventurepath { get; set; }
        public virtual ICollection<scenario> scenarios { get; set; }
        public virtual ICollection<allycard> allycards { get; set; }
        public virtual ICollection<armorcard> armorcards { get; set; }
        public virtual ICollection<blessingcard> blessingcards { get; set; }
        public virtual ICollection<itemcard> itemcards { get; set; }
        public virtual ICollection<spellcard> spellcards { get; set; }
        public virtual ICollection<weaponcard> weaponcards { get; set; }
        public virtual ICollection<barriercard> barriercards { get; set; }
        public virtual ICollection<henchmencard> henchmencards { get; set; }
        public virtual ICollection<monstercard> monstercards { get; set; }
        public virtual ICollection<villaincard> villaincards { get; set; }
    }
}
