//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class adventurepath
    {
        public adventurepath()
        {
            this.adventuredecks = new HashSet<adventuredeck>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<adventuredeck> adventuredecks { get; set; }
    }
}
