//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class adventuredeck
    {
        public adventuredeck()
        {
            this.cards = new HashSet<card>();
            this.scenarios = new HashSet<scenario>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AdventurePathId { get; set; }
        public int Index { get; set; }
    
        public virtual ICollection<card> cards { get; set; }
        public virtual adventurepath adventurepath { get; set; }
        public virtual ICollection<scenario> scenarios { get; set; }
    }
}
