//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public card()
        {
            this.characterdecks = new HashSet<characterdeck>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DeckId { get; set; }
        public int CardTypeId { get; set; }
    
        public virtual cardtype cardtype { get; set; }
        public virtual deck deck { get; set; }
        public virtual ICollection<characterdeck> characterdecks { get; set; }
    }
}
