//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class characterarmorcard
    {
        public int Id { get; set; }
        public int CharacterId { get; set; }
        public int ArmorCardId { get; set; }
        public int Count { get; set; }
    
        public virtual armorcard armorcard { get; set; }
        public virtual character character { get; set; }
    }
}
