//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PcgStorageEntities : DbContext
    {
        public PcgStorageEntities()
            : base("name=PcgStorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<party> parties { get; set; }
        public virtual DbSet<pcguser> pcgusers { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<subskill> subskills { get; set; }
        public virtual DbSet<power> powers { get; set; }
        public virtual DbSet<charactercard> charactercards { get; set; }
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<cardtype> cardtypes { get; set; }
        public virtual DbSet<adventurepath> adventurepaths { get; set; }
        public virtual DbSet<adventuredeck> adventuredecks { get; set; }
        public virtual DbSet<character> characters { get; set; }
        public virtual DbSet<scenario> scenarios { get; set; }
        public virtual DbSet<characterdeck> characterdecks { get; set; }
        public virtual DbSet<characterpower> characterpowers { get; set; }
        public virtual DbSet<characterskill> characterskills { get; set; }
        public virtual DbSet<characterscenario> characterscenarios { get; set; }
        public virtual DbSet<allycard> allycards { get; set; }
        public virtual DbSet<armorcard> armorcards { get; set; }
        public virtual DbSet<blessingcard> blessingcards { get; set; }
        public virtual DbSet<itemcard> itemcards { get; set; }
        public virtual DbSet<spellcard> spellcards { get; set; }
        public virtual DbSet<weaponcard> weaponcards { get; set; }
        public virtual DbSet<characterallycard> characterallycards { get; set; }
        public virtual DbSet<characterarmorcard> characterarmorcards { get; set; }
        public virtual DbSet<characterblessingcard> characterblessingcards { get; set; }
        public virtual DbSet<characteritemcard> characteritemcards { get; set; }
        public virtual DbSet<characterspellcard> characterspellcards { get; set; }
        public virtual DbSet<characterweaponcard> characterweaponcards { get; set; }
        public virtual DbSet<barriercard> barriercards { get; set; }
        public virtual DbSet<henchmencard> henchmencards { get; set; }
        public virtual DbSet<monstercard> monstercards { get; set; }
        public virtual DbSet<villaincard> villaincards { get; set; }
        public virtual DbSet<removedallycard> removedallycards { get; set; }
        public virtual DbSet<removedarmorcard> removedarmorcards { get; set; }
        public virtual DbSet<removedbarriercard> removedbarriercards { get; set; }
        public virtual DbSet<removedblessingcard> removedblessingcards { get; set; }
        public virtual DbSet<removedhenchmencard> removedhenchmencards { get; set; }
        public virtual DbSet<removeditemcard> removeditemcards { get; set; }
        public virtual DbSet<removedmonstercard> removedmonstercards { get; set; }
        public virtual DbSet<removedspellcard> removedspellcards { get; set; }
        public virtual DbSet<removedvillaincard> removedvillaincards { get; set; }
        public virtual DbSet<removedweaponcard> removedweaponcards { get; set; }
    }
}
