//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class party
    {
        public party()
        {
            this.characters = new HashSet<character>();
            this.removedallycards = new HashSet<removedallycard>();
            this.removedarmorcards = new HashSet<removedarmorcard>();
            this.removedbarriercards = new HashSet<removedbarriercard>();
            this.removedblessingcards = new HashSet<removedblessingcard>();
            this.removedhenchmencards = new HashSet<removedhenchmencard>();
            this.removeditemcards = new HashSet<removeditemcard>();
            this.removedmonstercards = new HashSet<removedmonstercard>();
            this.removedspellcards = new HashSet<removedspellcard>();
            this.removedvillaincards = new HashSet<removedvillaincard>();
            this.removedweaponcards = new HashSet<removedweaponcard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PcgUserId { get; set; }
    
        public virtual pcguser pcguser { get; set; }
        public virtual ICollection<character> characters { get; set; }
        public virtual ICollection<removedallycard> removedallycards { get; set; }
        public virtual ICollection<removedarmorcard> removedarmorcards { get; set; }
        public virtual ICollection<removedbarriercard> removedbarriercards { get; set; }
        public virtual ICollection<removedblessingcard> removedblessingcards { get; set; }
        public virtual ICollection<removedhenchmencard> removedhenchmencards { get; set; }
        public virtual ICollection<removeditemcard> removeditemcards { get; set; }
        public virtual ICollection<removedmonstercard> removedmonstercards { get; set; }
        public virtual ICollection<removedspellcard> removedspellcards { get; set; }
        public virtual ICollection<removedvillaincard> removedvillaincards { get; set; }
        public virtual ICollection<removedweaponcard> removedweaponcards { get; set; }
    }
}
