//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class party
    {
        public party()
        {
            this.partycharacters = new HashSet<partycharacter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PcgUserId { get; set; }
    
        public virtual pcguser pcguser { get; set; }
        public virtual ICollection<partycharacter> partycharacters { get; set; }
    }
}
