//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class removedmonstercard
    {
        public int Id { get; set; }
        public int Count { get; set; }
        public int PartyId { get; set; }
        public int MonsterCardId { get; set; }
    
        public virtual monstercard monstercard { get; set; }
        public virtual party party { get; set; }
    }
}
