//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class subskill
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int BaseSkillId { get; set; }
        public int Adjustment { get; set; }
    
        public virtual skill skill { get; set; }
    }
}
